import os

Import('env')

testenv = env.Clone()

#===== unittests_moteProbe

unittests_moteProbe = testenv.Command(
    'test_report_moteProbe.xml', [],
    'py.test unit_tests --junitxml $TARGET.file',
    chdir=os.path.join('openvisualizer', 'motehandler', 'moteprobe')
)

Clean(unittests_moteProbe, [Glob('*.log.*'), Glob('*.log')])

testenv.AlwaysBuild(unittests_moteProbe)
testenv.Alias('unittests_moteProbe', unittests_moteProbe)
