# DO NOT EDIT DIRECTLY!
# This file was generated automatically by GenStackDefines.py
# on Wed, 05 Feb 2020 10:54:32
#

components = {
   0: "NULL",
   1: "OPENWSN",
   2: "IDMANAGER",
   3: "OPENQUEUE",
   4: "OPENSERIAL",
   5: "PACKETFUNCTIONS",
   6: "RANDOM",
   7: "RADIO",
   8: "IEEE802154",
   9: "IEEE802154E",
  10: "SIXTOP_TO_IEEE802154E",
  11: "IEEE802154E_TO_SIXTOP",
  12: "SIXTOP",
  13: "NEIGHBORS",
  14: "SCHEDULE",
  15: "SIXTOP_RES",
  16: "OPENBRIDGE",
  17: "IPHC",
  18: "FRAG",
  19: "FORWARDING",
  20: "ICMPv6",
  21: "ICMPv6ECHO",
  22: "ICMPv6ROUTER",
  23: "ICMPv6RPL",
  24: "OPENUDP",
  25: "OPENCOAP",
  26: "CJOIN",
  27: "OPENOSCOAP",
  28: "C6T",
  29: "CEXAMPLE",
  30: "CINFO",
  31: "CLEDS",
  32: "CSENSORS",
  33: "CSTORM",
  34: "CWELLKNOWN",
  35: "UECHO",
  36: "UINJECT",
  37: "RRT",
  38: "SECURITY",
  39: "USERIALBRIDGE",
  40: "UEXPIRATION",
  41: "UMONITOR",
  42: "CINFRARED",
}

errorDescriptions = {
   1: "node joined",
   2: "OSCOAP sequence number reached maximum value",
   3: "OSCOAP buffer overflow detected (code location {0})",
   4: "OSCOAP replay protection failed",
   5: "OSCOAP decryption and tag verification failed",
   6: "Aborted join process (code location {0})",
   7: "unknown transport protocol {0} (code location {1})",
   8: "unsupported port number {0} (code location {1})",
   9: "invalid checksum, expected 0x{:04x}, found 0x{:04x}",
  10: "received an echo request",
  11: "received an echo reply",
  12: "the received packet has expired",
  13: "packet expiry time reached, dropped",
  14: "unexpected DAO (code location {0}). A change maybe happened on dagroot node.",
  15: "unsupported ICMPv6 type {0} (code location {1})",
  16: "unsupported 6LoWPAN parameter {1} at location {0}",
  17: "no next hop for layer 3 destination {0:x}{1:x}",
  18: "invalid parameter",
  19: "invalid forward mode",
  20: "large DAGrank {0}, set to {1}",
  21: "packet discarded hop limit reached",
  22: "loop detected due to previous rank {0} lower than current node rank {1}",
  23: "upstream packet set to be downstream, possible loop.",
  24: "packet to forward is dropped (code location {0})",
  25: "fragmentation buffer overflowed ({0} fragments queued)",
  26: "invalid original packet size ({0} > {1})",
  27: "reassembled fragments into big packet (size: {0}, tag: {1})",
  28: "fast-forwarded all fragments with tag {0} (total size: {1})",
  29: "stored a fragment with offset {0} (currently in buffer: {1})",
  30: "failed to send fragment with tag {0} (offset: {1})",
  31: "reassembly or vrb timer expired for fragments with tag {0}",
  32: "neighbors table is full (max number of neighbor is {0})",
  33: "there is no sent packet in queue",
  34: "there is no received packet in queue",
  35: "schedule overflown",
  36: "sixtop return code {0} at sixtop state {1}",
  37: "there are {0} cells to request mote",
  38: "the cells reserved to request mote contains slot {0} and slot {1}",
  39: "wrong celltype {0} at slotOffset {1}",
  40: "unsupported IEEE802.15.4 parameter {1} at location {0}",
  41: "got desynchronized at slotOffset {0}",
  42: "synchronized at slotOffset {0}",
  43: "large timeCorr.: {0} ticks (code loc. {1})",
  44: "wrong state {0} in end of frame+sync",
  45: "wrong state {0} in startSlot, at slotOffset {1}",
  46: "wrong state {0} in timer fires, at slotOffset {1}",
  47: "wrong state {0} in start of frame, at slotOffset {1}",
  48: "wrong state {0} in end of frame, at slotOffset {1}",
  49: "maxTxDataPrepare overflows while at state {0} in slotOffset {1}",
  50: "maxRxAckPrepapare overflows while at state {0} in slotOffset {1}",
  51: "maxRxDataPrepapre overflows while at state {0} in slotOffset {1}",
  52: "maxTxAckPrepapre overflows while at state {0} in slotOffset {1}",
  53: "wdDataDuration overflows while at state {0} in slotOffset {1}",
  54: "wdRadio overflows while at state {0} in slotOffset {1}",
  55: "wdRadioTx overflows while at state {0} in slotOffset {1}",
  56: "wdAckDuration overflows while at state {0} in slotOffset {1}",
  57: "security error on frameType {0}, code location {1}",
  58: "getData asks for too few bytes, maxNumBytes={0}, fill level={1}",
  59: "the input buffer has overflown",
  60: "busy sending",
  61: "sendDone for packet I didn't send",
  62: "no free packet buffer (code location {0})",
  63: "no free timer or queue entry (code location {0})",
  64: "freeing unused memory",
  65: "freeing memory unsupported memory",
  66: "unsupported command {0}",
  67: "unknown message type {0}",
  68: "wrong address type {0} (code location {1})",
  69: "bridge mismatch (code location {0})",
  70: "header too long, length {1} (code location {0})",
  71: "input length problem, length={0}",
  72: "booted",
  73: "invalid serial frame",
  74: "invalid packet from radio, length {1} (code location {0})",
  75: "busy receiving when stop of serial activity, buffer input length {1} (code location {0})",
  76: "wrong CRC in input Buffer",
  77: "synchronized when received a packet",
  78: "the slot {0} to be added is already in schedule",
  79: "the received packet format is not supported (code location {0})",
  80: "the metadata type is not suppored",
  81: "maxretries reached (counter: {0})",
  82: "empty queue or trying to remove unknown timer id (code location {0})",
}

sixtop_returncode = {
   0: "RC_SUCCESS",
   1: "RC_EOL",
   2: "RC_ERROR",
   3: "RC_RESET",
   4: "RC_VER_ERR",
   5: "RC_SFID_ERR",
   6: "RC_SEQNUM_ERR",
   7: "RC_CELLLIST_ERR",
   8: "RC_BUSY",
   9: "RC_LOCKED",
}

sixtop_statemachine = {
   0: "IDLE",
   1: "WAIT_ADDREQUEST_SENDDONE",
   2: "WAIT_DELETEREQUEST_SENDDONE",
   3: "WAIT_RELOCATEREQUEST_SENDDONE",
   4: "WAIT_COUNTREQUEST_SENDDONE",
   5: "WAIT_LISTREQUEST_SENDDONE",
   6: "WAIT_CLEARREQUEST_SENDDONE",
   7: "WAIT_ADDRESPONSE",
   8: "WAIT_DELETERESPONSE",
   9: "WAIT_RELOCATERESPONSE",
  10: "WAIT_COUNTRESPONSE",
  11: "WAIT_LISTRESPONSE",
  12: "WAIT_CLEARRESPONSE",
}
