# DO NOT EDIT DIRECTLY!
# This file was generated automatically by GenStackDefines.py
# on Sat, 23 Mar 2019 18:19:18
#

components = {
   0: "NULL",
   1: "OPENWSN",
   2: "IDMANAGER",
   3: "OPENQUEUE",
   4: "OPENSERIAL",
   5: "PACKETFUNCTIONS",
   6: "RANDOM",
   7: "RADIO",
   8: "IEEE802154",
   9: "IEEE802154E",
  10: "SIXTOP_TO_IEEE802154E",
  11: "IEEE802154E_TO_SIXTOP",
  12: "SIXTOP",
  13: "NEIGHBORS",
  14: "SCHEDULE",
  15: "SIXTOP_RES",
  16: "OPENBRIDGE",
  17: "IPHC",
  18: "FORWARDING",
  19: "ICMPv6",
  20: "ICMPv6ECHO",
  21: "ICMPv6ROUTER",
  22: "ICMPv6RPL",
  23: "OPENUDP",
  24: "OPENCOAP",
  25: "CJOIN",
  26: "OPENOSCOAP",
  27: "C6T",
  28: "CEXAMPLE",
  29: "CINFO",
  30: "CLEDS",
  31: "CSENSORS",
  32: "CSTORM",
  33: "CWELLKNOWN",
  34: "UECHO",
  35: "UINJECT",
  36: "RRT",
  37: "SECURITY",
  38: "USERIALBRIDGE",
  39: "UEXPIRATION",
  40: "UMONITOR",
  41: "CINFRARED",
}

errorDescriptions = {
   1: "received an echo request",
   2: "received an echo reply",
   3: "getData asks for too few bytes, maxNumBytes={0}, fill level={1}",
   4: "the input buffer has overflown",
   5: "the command is not allowed, command = {0}",
   6: "unknown transport protocol {0} (code location {1})",
   7: "unsupported port number {0} (code location {1})",
   8: "unexpected DAO (code location {0}). A change maybe happened on dagroot node.",
   9: "unsupported ICMPv6 type {0} (code location {1})",
  10: "unsupported 6LoWPAN parameter {1} at location {0}",
  11: "no next hop for layer 3 destination {0:x}{1:x}",
  12: "invalid parameter",
  13: "invalid forward mode",
  14: "large DAGrank {0}, set to {1}",
  15: "packet discarded hop limit reached",
  16: "loop detected due to previous rank {0} lower than current node rank {1}",
  17: "upstream packet set to be downstream, possible loop.",
  18: "packet to forward is dropped (code location {0})",
  19: "neighbors table is full (max number of neighbor is {0})",
  20: "there is no sent packet in queue",
  21: "there is no received packet in queue",
  22: "schedule overflown",
  23: "wrong celltype {0} at slotOffset {1}",
  24: "unsupported IEEE802.15.4 parameter {1} at location {0}",
  25: "got desynchronized at slotOffset {0}",
  26: "synchronized at slotOffset {0}",
  27: "large timeCorr.: {0} ticks (code loc. {1})",
  28: "wrong state {0} in end of frame+sync",
  29: "wrong state {0} in startSlot, at slotOffset {1}",
  30: "wrong state {0} in timer fires, at slotOffset {1}",
  31: "wrong state {0} in start of frame, at slotOffset {1}",
  32: "wrong state {0} in end of frame, at slotOffset {1}",
  33: "maxTxDataPrepare overflows while at state {0} in slotOffset {1}",
  34: "maxRxAckPrepapare overflows while at state {0} in slotOffset {1}",
  35: "maxRxDataPrepapre overflows while at state {0} in slotOffset {1}",
  36: "maxTxAckPrepapre overflows while at state {0} in slotOffset {1}",
  37: "wdDataDuration overflows while at state {0} in slotOffset {1}",
  38: "wdRadio overflows while at state {0} in slotOffset {1}",
  39: "wdRadioTx overflows while at state {0} in slotOffset {1}",
  40: "wdAckDuration overflows while at state {0} in slotOffset {1}",
  41: "busy sending",
  42: "sendDone for packet I didn't send",
  43: "no free packet buffer (code location {0})",
  44: "freeing unused memory",
  45: "freeing memory unsupported memory",
  46: "unsupported command {0}",
  47: "unknown message type {0}",
  48: "wrong address type {0} (code location {1})",
  49: "bridge mismatch (code location {0})",
  50: "header too long, length {1} (code location {0})",
  51: "input length problem, length={0}",
  52: "booted",
  53: "invalid serial frame",
  54: "invalid packet frome radio, length {1} (code location {0})",
  55: "busy receiving when stop of serial activity, buffer input length {1} (code location {0})",
  56: "wrong CRC in input Buffer",
  57: "synchronized when received a packet",
  58: "security error on frameType {0}, code location {1}",
  59: "sixtop return code {0} at sixtop state {1}",
  60: "there are {0} cells to request mote",
  61: "the cells reserved to request mote contains slot {0} and slot {1}",
  62: "the slot {0} to be added is already in schedule",
  63: "the received packet format is not supported (code location {0})",
  64: "the metadata type is not suppored",
  65: "the received packet has expired",
  66: "packet expiry time reached, dropped",
  67: "node joined",
  68: "OSCOAP sequence number reached maximum value",
  69: "OSCOAP buffer overflow detected (code location {0})",
  70: "OSCOAP replay protection failed",
  71: "OSCOAP decryption and tag verification failed",
  72: "Aborted join process (code location {0})",
  73: "uinject packet (counter: {0}) is dropped",
}

sixtop_returncode = {
   0: "RC_SUCCESS",
   1: "RC_EOL",
   2: "RC_ERROR",
   3: "RC_RESET",
   4: "RC_VER_ERR",
   5: "RC_SFID_ERR",
   6: "RC_SEQNUM_ERR",
   7: "RC_CELLLIST_ERR",
   8: "RC_BUSY",
   9: "RC_LOCKED",
}

sixtop_statemachine = {
   0: "IDLE",
   1: "WAIT_ADDREQUEST_SENDDONE",
   2: "WAIT_DELETEREQUEST_SENDDONE",
   3: "WAIT_RELOCATEREQUEST_SENDDONE",
   4: "WAIT_COUNTREQUEST_SENDDONE",
   5: "WAIT_LISTREQUEST_SENDDONE",
   6: "WAIT_CLEARREQUEST_SENDDONE",
   7: "WAIT_ADDRESPONSE",
   8: "WAIT_DELETERESPONSE",
   9: "WAIT_RELOCATERESPONSE",
  10: "WAIT_COUNTRESPONSE",
  11: "WAIT_LISTRESPONSE",
  12: "WAIT_CLEARRESPONSE",
}
