"""
SConscript to run the unittests.
"""


import os

Import('env')

testEnv = env.Clone()

test_suite = testEnv.Command('test_report.xml', [], 'py.test unittests --junitxml $TARGET.file', chdir=os.path.join('tests'))
Clean(test_suite, [Glob('*.log.*'), Glob('*.log')])

testEnv.AlwaysBuild(test_suite)
testEnv.Alias('unittests', test_suite)
